name: Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  pull_request:
    branches-ignore:
      - main
jobs:
  Deploy-Preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Install ZX
        run: npm i -g zx
      - name: Deploy Project Artifacts to Vercel
        env:
          NX_VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          NX_VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          NX_VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: zx ./scripts/deploy-preview.mjs
